### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [PolarGoose/ShowWhatProcessLocksFile#2]
Does this, or an earlier version, work with Win7?

Thanks

**Comment by PolarGoose** [comment]
Hello @harryray33,

Windows 7 is no longer supported by MS. Also I have problems installing Windows 7 in Hyper-V to test.
I think that it should work if you have `.Net Framework 4.6.2` or higher installed.

If you try, please share the results.

**Comment by PolarGoose** [comment]
I have tested it:
Unfortunately the program doesn't work because [Handle2](https://github.com/PolarGoose/Handle2) fails to start, most probably because it uses some WinApi call that is not available on Windows 7 or the toolchain that was used to compile it doesn't support Windows 7.
As Windows 7 is no longer supported by Microsoft, I don't see value in investing effort to support it.

**Comment by PolarGoose** [comment]
@harryray33,
If your issue is still relevant:
I have created a new release that uses the Sysinternals Handle tool under the hood. I think it should allow the app to run on Windows 7.
Could you please check if it works?

**Comment by harryray33** [comment]
Thanks, I'll try it out

**Comment by PolarGoose** [comment]
@harryray33,
I have tested it on Windows 7. It works.
So, I'm going to close this issue.
