### ISSUE TITLE
Unit tests failed

### ISSUE THREAD

**Issue by Polar-Pumpkin** [PolarGoose/ShowWhatProcessLocksFile#5]
Hi, when I tried to run it, I found that it could not retrieve any locked files. So I ran the unit tests and found that all the tests that should return information failed. Furthermore, through breakpoints, I found that the `SafeProcessHandle` it obtained through `WinApi.OpenProcess` was invalid (`IsInvalid` is `true`), and finally returned an empty list.

![Snipaste_2024-08-26_18-28-05](https://github.com/user-attachments/assets/e4278867-b201-43de-93a5-29b6c4c782b8)

Thank you very much for any help!

- - -

UPDATE

Sorry to bother you, I may have misunderstood some information, I will investigate further and reply

**Comment by Polar-Pumpkin** [comment]
I noticed that not all `SafeProcessHandle` were invalid, but the unit test still failed. 😢

**Comment by PolarGoose** [comment]
Hello @Polar-Pumpkin,

Thank you for the report. I'm looking into it.

What is the reason you decided to dig into the unit tests?

**Comment by PolarGoose** [comment]
I have checked:
* All tests run on my machine (Windows 11 Pro)
* It is ok for a `WinApi.OpenProcess` function to return an invalid handle. This means that it failed to open a process because, most probably, this process is run from an admin. `NtDll.QuerySystemHandleInformation` returns handles of all processes in the system regardless of whether you have rights to access them. Therefore, some handles are skipped because they belong to the process we can't access.
* I think it is okay if some unit tests fail because they rely on the fact that some files should be locked on your system. This might not be the case. The files I have chosen are locked on my system by OS processes like `explorer.exe`. It is not guaranteed that they will be locked on your system.

**Comment by Polar-Pumpkin** [comment]
In fact, I'm trying in my .NET Framework project implements the function of detecting locked files, but I found that all 'SafeProcessHandle' returned by my 'OpenProcess' method is invalid. Then I ran a unit test to check whether your software also has this situation. 

At first, I thought it return an empty list, and then I found that your software could get a valid 'SafeProcessHandle' in the same process. Now it seems that this is one of the differences between .NET Framework project and .NET Core project. 😢 

I'm very sorry for taking up your time, and thank you very much for explaining these problems to me.

**Comment by PolarGoose** [comment]
@Polar-Pumpkin,

It shouldn't depend on .Net Framework or .Net Core. I have tested that the code also works with `<TargetFramework>net8.0-windows</TargetFramework>`.
It is strange that you can't open any of the processes. Try to run Visual Studio as an admin then you should be able to open more processes.

**Comment by Polar-Pumpkin** [comment]
I have tried to run compiled programs with administrator privileges, but the SafeProcessHandle listed is still invalid.

The .csproj format of the .NET Framework project and the .NET project I mentioned is different. It seems to be called the new SDK-style project.

**Comment by PolarGoose** [comment]
There is an alternative way:
You can take [Sysinternals Handle](https://learn.microsoft.com/en-us/sysinternals/downloads/handle). It can output locking information in CSV so that you can run it from your C# application and parse its output.

Also, you can use GitHub search to find code samples that you can use as a reference. For instance, you can search for the usages of `QuerySystemHandleInformation`

**Comment by Polar-Pumpkin** [comment]
Thank you very much for your help! 🥰
